# fly.toml file generated for loveislove on 2023-04-05T22:43:36+02:00

app = "loveislove"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "ams"
processes = []

[build]
  image = "herodan/datingapp:latest"

[env]
ASPNETCORE_URLS = "http://+:8080"
CloudinarySettings__CloudName = "dmfaujmg3"
CloudinarySettings__ApiKey = "363295318999856"



[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
